[package]
name = "guitar_pedal"
version = "0.1.0"
authors = ["aujxn <ajn6@pdx.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jack = "0.6"
hound = "3.4"
structopt = "0.3"
ringbuf = "0.2"
